### ISSUE TITLE
GTV3 CPP (MANNEQUIN SIGNS CUSTOM ITEMS DISPLAY BLOCK)

### ISSUE THREAD

**Issue by gtv4** [GrowtopiaNoobs/GrowtopiaServer#1101]
cpp file with code is GTV3.cpp
(and PlayerDefs.h)

github repo:
https://github.com/gtv3man/GTV3

Download links:
https://www104.zippyshare.com/v/11OkVvup/file.html
https://mega.nz/#!qLInha5T!A8GLZDPziiGE6z57R1uQu-0T6vGEuASJmDWb4gz95Nc
https://anonfile.com/z8ua57Jbn1/GTV3-master_rar

[GTV3-master.zip](https://github.com/GrowtopiaNoobs/GrowtopiaServer/files/4007013/GTV3-master.zip)

**Comment by playingo** [comment]
its the old 0.15 source that got leaked by ness and we talked to anybody so that people who get the source are not able to compete/make money with it. which should be done by anybody updating the source to the newest features especially the one that are already leaked. the decoder has been published already and we are still waiting for the rest, maybe there is no "rest" and the decoder was everything

**Comment by gtv4** [comment]
core framework = up to date with leaked features mm......
gtv3 literally broke his tos, keeping these kinds of features private
instead of sharing them. I am only doing the community a favor by sharing
these features with everyone.

**Comment by gtdk** [comment]
well, u have this but how tf we gonna get exe or smth

**Comment by playingo** [comment]
core framework isnt up to date anymore i dont filter the way i did inb4 + no npcs + no items.dat encoding + im kinda think anybody wouldnt have wanted me to share the source otherwise he would have shared his items.dat decoding inb4 aswell and he had a couple deals with vyte so

**Comment by gtv4** [comment]
how is it not up to date? its literally a core framework, not a fully
developed server with all the features u now so dearly want leaked.
couple of deals with vyte = sold item decoder/encoder/whatever but will
make it public at a later time which he obviously now did & will get paid
for coding his server

**Comment by playingo** [comment]
@gtv4 no gem merging in the old version so

**Comment by gtv4** [comment]
wow literally 1 small thing now that changes everything!!! green key level
argument

**Comment by noobes1337** [comment]
https://github.com/noobes1337/GTPS-Source-Leaks

**Comment by playingo** [comment]
@noobes1337 wtf ur trying to be so cool

**Comment by noobes1337** [comment]
retard

**Comment by playingo** [comment]
retard urself ur trying to be so cool ur arrogance just increased by 200% again everyone knows ur a script kiddie no need to defend urself

**Comment by MarmoriPelaa** [comment]
Here we go again. Playingo flexing with his team against one individual who can do the same all by themselves. Give up already. You are here to just insult people. You are not helping anyone.

**Comment by playingo** [comment]
I didnt flex in here? Do u think noobesgt is meant to be the individual? hell naw, literally copied parts of our leaked old source and its the opposite, do you know who gtv4 even is? its amateurz who tries to make the source popular so hard, which is good cuz the ppl cant sell the codes for money/cant compete and actually use it normally

**Comment by MarmoriPelaa** [comment]
You are the one who does absolutely nothing wrong? You are getting angry when people finding out stuff about the private server, or if you have found out something then you just be like: "lmao this one's leaked source by X". Why bother? In general, your code should be "leaked" but nope, you are the one making a *public* private server without sharing the source in *public* which is as illegal as the others. The key thing here is you don't help anyone so get out. You are the one who makes the community toxic by insulting them to the point they give up. You always have to be the winner of each fight and you do not care anyone else. I'm here to fight against you just for the others because you are causing mental pain to them.

**Comment by playingo** [comment]
first of all, anybody's private server source wasnt even supposed to be open source (i talked to ama back then). second of all, of course I dont have anything against when people find out new stuff, it's just sad to see people sharing their new/secret stuff to people like noobesgt (people who cannot have done it themselves as they are too lazy and dont deserve stuff imo). thats how trash the community is.

**Comment by playingo** [comment]
Also lets not forget how "illegal" (according to you) it is, to even be involved with private servers, according to ubisoft, so your "illegal" argument does not count

**Comment by OverallGod** [comment]
Lmao Im so glad I stopped thinking about this game and server. Yall should just stop, In the future none of this is going to matter. @playingo I get it bro Its your work they didnt put in the time or effort but fr life isnt fair so just get over it. @MarmoriPelaa Thanks for trying to make this toxic place a little better but you just started an argument and honestly its not going to make a difference, everyone need to grow tf up its literally a game calm down.

**Comment by playingo** [comment]
@OverallGod true words bro

**Comment by gtv4** [comment]
https://i.imgur.com/dX4722D.png

**Comment by iProgramMC** [comment]
@MarmoriPelaa this is not playingo, this is amateurz on an alt (@ama6nen)

**Comment by iProgramMC** [comment]
btw @gtv4 it really is a separate codebase from GTV3 so we are NOT required to release our source code under ANY means.

**Comment by iProgramMC** [comment]
by the way @MarmoriPelaa most server developers here do NOT know what they are doing (the people who beg for code) so you are not allowed to defend them by saying "they can do it all by themselves" when they are really not capable of doing so (at least not at the moment you're claiming this, they may learn C++)

**Comment by gtv4** [comment]
its not seperate codebase lol have u looked at the code for even a minute?

**Comment by iProgramMC** [comment]
@gtv4 our new server we are coding right now is a separate codebase

**Comment by iProgramMC** [comment]
@yikesr @Cojeb please take down your gtv3man forks or I will be forced to dmca strike you just like I did gtv3man's

**Comment by GuckTubeYT** [comment]
> @yikesr @Cojeb please take down your gtv3man forks or I will be forced to dmca strike you just like I did gtv3man's

Wtf man, i need that cpp

**Comment by OverallGod** [comment]
@iProgramMC dont worry @yikesr its gone

**Comment by iProgramMC** [comment]
@GuckTubeYT Too bad we took it down. Soon we are going to file a complaint about it on ZippyShare, MEGA.NZ and YouTube.

**Comment by iProgramMC** [comment]
This is so no traces of a GTV3 source code leak occur.

**Comment by iProgramMC** [comment]
@OverallGod Thanks for respecting our work!

**Comment by Cojeb** [comment]
The GTV3 fork is no longer available. :+1:

**Comment by iProgramMC** [comment]
btw @gtv3man is a retard for claiming Growalone as well 🤦‍♂️

**Comment by iProgramMC** [comment]
@Cojeb thanks!! Now I will warn @noobes1337 about a potential DMCA strike on his account if he does not remove GTV3.rar from his repo GTPS-Source-Leaks. I know he wants to act much more condescendingly, but I will stop him right there.

**Comment by Cojeb** [comment]
Got rid of that fork.

**Comment by OverallGod** [comment]
@iProgramMC No problem, I try to be as respectful online as I can. And it wasnt very nice of @gtv3man to leak your stuff

**Comment by iProgramMC** [comment]
I know it was not nice. I am now going on a rampage of threats to remove as much GTV3 source code leaks as possible but it is still possible that he is going to come back.

**Comment by Cojeb** [comment]
Is a problem if fork was made private and (will be held private)?

**Comment by OverallGod** [comment]
hey @iProgramMC would it be okay if I ran your server locally, Ive never had any intent for others to connect I kinda just do this for fun. On my server that I didnt release or let anyone else play on. I have mysql database setup on it using mysql c++ connector and its interesting how you solved some of my problems.

**Comment by ama6nen** [comment]
Useless rampage of threats because of counter dmca, and if you want to take
it down again you will have to file a lawsuit after that, which you dont
have a legal basis for as gtv3 is not a registered copyrighted work

**Comment by gtv4** [comment]
You are stupid if u think "no traces will be left" its gonna be reuploaded
faster than u can make any complaints
And theres no basis for taking it down in zippyshare/mega/youtube/etc
because its quite literally a download which doesnt mention anything about
leaks.
+ useless "rampage of threats" because of counter dmca, and if you want to
take
it down again you will have to file a lawsuit after that, which you dont
have a legal basis for as its not a registered copyrighted work

**Comment by willi123yao** [comment]
Seriously, enough of this drama. Nothing here is "leaked" in the first place and this should not be happening. @GrowtopiaNoobs released this repository code under the [GNU Affero General Public License](https://www.gnu.org/licenses/agpl-3.0.en.html), which clearly states 2 things and first is that **any modifications or derived works**  (which includes your own private servers if they use code from this repository) will also be licensed under GNU Affero General Public License. 

Secondly, the [GNU Affero General Public License](https://www.gnu.org/licenses/agpl-3.0.en.html) clearly states that network usage (in this case, hosting a server) is considered **distribution** and thereby you are **required** to provide your source code **with modifications** used currently on the network to the users.

@iProgramMC Clearly you are violating your rights and the license of this work given to you, and you are duly expected to provide your source publicly to your users. Any modifications to the original code and that is required to run the server **will be licensed under GPL**, although you can add your own copyright notice **below the original notice** for those who wish to **respect and use** your work for their own projects, letting them seek consent from the respective copyright holders involved. However, this does not change the fact that the code is still recognised under the [GNU Affero General Public License](https://www.gnu.org/licenses/agpl-3.0.en.html) and you are **required to publish all your changes upon modification** for your network users.

I would like to make this clear that open source does not mean free source, and any works under open source licenses can be still protected by copyright laws. Open source means that the source is available for everyone to see and view, but its usage (whether in your own projects/servers or other things such as derived works) will still requires you to follow the licenses stated and provided.

For those involved here and to anybody else concerned about this, I highly suggest you to read and understand fully about the terms and conditions as governed by the [GNU Affero General Public License](https://www.gnu.org/licenses/agpl-3.0.en.html), before complaining about getting your code "leaked" over here.

**Comment by WoofHax** [comment]
2020 of drama

**Comment by iProgramMC** [comment]
@willi123yao This does not mean that the new server we are working on needs to be released, as we are not basing it off your code anymore.

**Comment by iProgramMC** [comment]
@willi123yao We have the choice to release our source code instead of having it leaked for us by other people.  First off, we put in time and effort for something Indonesian script kiddies will copy because of the license and make profit off our work.  We don't want this, so it's alright that I've DMCA striked the GTV3man's repository

**Comment by iProgramMC** [comment]
We are going to release it again soon, so there is no need to complaint.

**Comment by iProgramMC** [comment]
@willi123yao How do we defend ourselves from having our code used without credit?

**Comment by iProgramMC** [comment]
@gtv4 If you are going to release our source code then at least credit us instead of taking credit. I still have the right to DMCA strike you because you claim our work which is open source.

**Comment by iProgramMC** [comment]
@gtv4 And you are a retard for claiming Growalone. Get r/quityourbullshit-ed.

**Comment by DEERUX** [comment]
let me clear some things up:
about ama claiming codebase is not different; false, 0.15 is an old source code with the basics and more yes, the code base got changed alot in 0.20 and entirely changed in our c# source "real gt server clone"
about willi123yao; its unfair in some shit gt community like this to always publish our source when we dont want people to know or have everything they didnt do any work for. people should be desired to get stuff and the only people who are/is desired to get it is anybody/gt noobs and iprogramincpp and possibly mar4ello6. and im purely talking about those 3 people rn, im not including any other people.
3. ama is putting too much effort to harm us meanwhile doesnt know we actually dont care cause I am able to change subjects and projects at any time without caring at all.
4. anybody is about to share some new server code which, he already published the decoder, i dont wanna say its because of us or smth but I believe we/ama sped this up. aswell as anybodys new server code which will according to him come out soon
5. not everything has been leaked yet and there is still like a darn huge ton of stuff we may know and others dont. not even the newest gtv3 source has it and i would say probably with only possibility the current c# source may only have it which we are working on with iprogramincpp and it doesnt rely on any of anybodys great work or yao's.

**Comment by iProgramMC** [comment]
@DEERUX @willi123yao We should allow people to use our code so long as they mention us where it is easily visible. If it is not, we should contact them and shut their server down or have them mention us.

**Comment by DEERUX** [comment]
yeah this should only apply to the 0.15 source not willing to share newest source or depends on anybody idk... go to dms btw

**Comment by WoofHax** [comment]
@DEERUX I am not sure is that C# safe to use?

**Comment by DEERUX** [comment]
c# is a more beginner/amateur friendly language and if you know how to deal with the language, why would it be unsafe to use? only cons would be .NET dependency but we are fine with it.

**Comment by OverallGod** [comment]
This server is a mess, I really hope when the new source gets released that we can all work together as a team to make it the best possible. You need to stop competing with each other, its not a race or a competition its a god damn server. No one should be buying or selling anything in game for real currency because its absolutely wrong to make money off of this.

**Comment by gtv4** [comment]
[that moment when u say u dont care but u write 9 paragraphs]
also, ur still breaking anybody's license by not releasing ur "0.2.0" which
has like 3 more features :)

**Comment by DEERUX** [comment]
@gtv4 u dont know how many x features the 'newest gtv3 source is' so what u just did there is guessing except u have the source which might be possible as I gave my newest gtv3 source to anybody already and he will decide what 2 do with it of course u had to be classic ama and make pre claims already because u are way too confident about what u say.

**Comment by DEERUX** [comment]
but when the case is where u do the false claim no1 gives a shit xD

**Comment by gtv4** [comment]
u mean false claims what u constantly say?
+ only thing u have added is like /test1 0.1% working npc spawning and some
useless half done shit once again

**Comment by MarmoriPelaa** [comment]
> @willi123yao We have the choice to release our source code instead of having it leaked for us by other people. First off, we put in time and effort for something Indonesian script kiddies will copy because of the license and make profit off our work. We don't want this, so it's alright that I've DMCA striked the GTV3man's repository

I highly doubt they would make anything from the code you would give them. If they barely can code, how the heck do you think they can do anything else related, such as money off it. What I'm trying to say is that they aren't even able to setup any kind of profitable payment system that would work nor can they even advertise it in any way so there's no worry for that. Again, GrowtopiaNoobs didn't even want money for the source, but you shitheads just want every single penny off of everything that exists while GrowtopiaNoobs should own all the profit you've ever earned from the project. That is, if the world used YOUR logic.

I'm signing off now. Thankfully, you'll now be getting rid of me for... months? weeks? days? You decide how long, but I will be off of this project for some time and after that see if anything's gotten better, or if this repo is closed because of the shitty part of the community. I really hope for the former, but I still do think the latter is the most likely thing that's going to happen. I have high doubts of this repository recovering any time soon.

**Comment by DEERUX** [comment]
@MarmoriPelaa what we are trying to say is people who do something for real and have interest, no matter if its based on anyone else's work, but what im trying to say is that people who do something and invest time (those who paste clearly arent interested in anything and clearly dont work hard or maybe work more than slightly) should get rewarded. and does who don't should not, and anyone can do something its the most retarded thing i would hear something in human history when a human says: YEAH BUT THERE ARE HUMAN RIGHTS EVERYONE SHOULD GET REWARDED!!!, that would be so retarded and its an excuse, ANYONE can do anything they wanna do, some are limited, some are not. And if they expect some money out of their hardwork its fully okay, and I have mentioned above what definitely is not defined as "hardwork or even work". Those who do nothing and expect rewards, in that case its not okay!!! and dont come me with arguments like that or smth in the end its so sad that 70% of people work so they can ripoff other people and thats how capitalism works, and very good example in here aswell as u can see with the GTPD GTXX GTLO GTSOMETHING PCOLD PROJECT WHATEVER are all based on that, at least gtv3 had work put in, and im not even worried that I didn't include a word like "some", "tiny" or "minior" because IT HAD A LOT OF WORK IN IT (otherwise we would have ended up like some indog server or smth) and we clearly had a feature-rich server.

**Comment by gtv4** [comment]
" PROJECT WHATEVER"
You mean, like "Project Realistic", "Project Realism", "Project "Reality"",
which all by you? (gtv3, gtv3 again but after src leak, some stealer shit=
Also, I fully agree that limited people like playingo should not be bullied
for that even if they are extremely limited like him!!

**Comment by DEERUX** [comment]
had to edit github comment like 3 times due to mistakes in the sentence**

**Comment by DEERUX** [comment]
@gtv4 it aint for stealer shit u dont even know the back story of it and the back story of it is that I was trying to implement pass hashing but failed many times (it didnt like my pass or smth it just didnt work) even with filtering the hashed output so I was forced to wait and look for different alternatives. to that point I didnt have any database related security yet and yes it's been better but it was no one's purpose to steal passwords or anything. Most people used different passes / account names either, no one thought of any stealing.

**Comment by gtv4** [comment]
it was 100% the purpose of stealing stop deluding urself
"Remotely Host (A TCP Server for your spreaded clients) and Manage a
professional save.dat stealer with extra features and Simple-AAP Bypass for
free."
Straight up from your github repo

**Comment by DEERUX** [comment]
Oh you talkin about the saveforwader ripoff hell yeah that was the purpose of it but not related to gtv3, that is a different thing.

**Comment by gtv4** [comment]
so u accidentally revealed that u were stealing passwords with gtv3 too?
nice.

**Comment by DEERUX** [comment]
oh what!? no ofc not!!

**Comment by DEERUX** [comment]
as i said i didnt hack/went into a single account through gtv3 it wa sjust the lazyness of me that i couldnt implement hashing

**Comment by gtv4** [comment]
damage control

**Comment by DEERUX** [comment]
whats ur issue now

**Comment by DEERUX** [comment]
huh okay whatever u mean with that or whatever is ur problem sir, wont bother with it

**Comment by gtv4** [comment]
that moment when u dont care but u keep replying and writing essays am i
right

>

**Comment by DEERUX** [comment]
yeah well I do not care about the source or something but I am allowed to write back. interesting for me is arent u getting tired or something when putting that much effort into 1 guy or smth like i still dont understand til 2 day but aight.

**Comment by gtv4** [comment]
because ur ego quite literally does not allow u to not lie/not correct
something/not say random shit/not flex with useless shit and that situation
hasnt changed for years

**Comment by DEERUX** [comment]
Dude lies arent bad especially on the internet it provides you security aswell. plus about that shitty dll i scammed someone with it who offered me a fake "punch to disconnect people" "opcode" so he can get smth else for free at that point it was my purpose of scamming him + maybe u didnt notice that the "internal leak" video is literally smth i made fun of myself cuz guess what all I gave nabsi is an external version spoofer and an external "executor" my shit looks differently and lol they managed to use imgui now and obviously its also what i simply just gave them its none of my business

**Comment by DEERUX** [comment]
perhaps if u want u can show me some of my pics u took on discord and ill clear them up and if theres nothing to clear up ill just say that its smth true and nothing else.

**Comment by gtv4** [comment]
see this is my point

**Comment by DEERUX** [comment]
yeah so your point is what specifically?

**Comment by gtv4** [comment]
>interesting for me is arent u getting tired or something when putting that
much effort into 1 guy or smth like that i still dont understand til 2 day
but aight.
>because ur ego quite literally does not allow u to not lie/not correct
something/not say random shit/not flex with useless shit and that situation
hasnt changed for years

**Comment by DEERUX** [comment]
i originally wanted to be more of some kinda guy who shows how something works or like how to do stuff or just generally tutorials but that didnt seem to go well so its what im doing rn, the opposite.

**Comment by gtv4** [comment]
changes literally nothing

**Comment by DEERUX** [comment]
plus I can explain that alot of stuff u probs misunderstand because they arent usually some bad lies some are made because I wanted to allow myself some "social fun" and went trolling/confusing/making (sarcastic) jokes and I can give you a good example.
for instance, you got a picture where I claimed that "hamumu would have leaked the items.dat key and decoder and everything etc." which is obviously a troll/prank cuz it was related to what I told sebia (I was having some kinda fun and went trolling him): 
![38CFE95A-C72F-4C37-9647-A894E02A86DF](https://user-images.githubusercontent.com/59503175/71786146-d46ce780-3008-11ea-8640-01e4dd4c99e2.png)
![F5783D62-A30C-4EE4-9D96-1A1051991258](https://user-images.githubusercontent.com/59503175/71786148-d46ce780-3008-11ea-9abe-e0b673a0694b.png)
or for example that shitty filtering code used in gtv3 0.15 (its got remade in 0.16) which isnt even my code and it was nabsi's, i was busy with other stuff. and for example u might not know that we now actually use a loop and an array of characters to do this.

**Comment by gtv4** [comment]
ur literally being a clown by just trying to justify ur shit
this is exactly what I was talking about, how ur ego just won't let u not
act like a total clown who has to justify everything and never admit
anything and lie constantly

**Comment by DEERUX** [comment]
lies are powerful in the digital world bro

**Comment by WoofHax** [comment]
too many raterad at here

**Comment by DEERUX** [comment]
wouldnt use words like retarded because you might not know how it ends up but I would say that ye most people who participate in here are usually those who use the source themselves.

**Comment by WoofHax** [comment]
@DEERUX ik this is you cpp and you are hard working with nabsi and you teammate but don't become a toxic guys at here

**Comment by DEERUX** [comment]
1. yes
2. "cpp"
3. not toxic
4. im not working with nabsi, the one i am truly working with successfully is iprogramincpp.

**Comment by iProgramMC** [comment]
our problem is gtv3man and his crew claiming gtv3 as their own project when we worked on it not them

**Comment by WoofHax** [comment]
@gtv4 and you can close this issues bcz this is not issues and don't put bug label

**Comment by GuckTubeYT** [comment]
> 
> 
> @gtv4 and you can close this issues bcz this is not issues and don't put bug label

yeah

**Comment by iProgramMC** [comment]
> that moment when u dont care but u keep replying and writing essays am i right
> […](#)

no you aren't right 🙃

**Comment by gtv4** [comment]
wrong + why the fuck are u replying this much later when the conversation
is done

**Comment by iProgramMC** [comment]
Idk, just messing around y'know 🙃

**Comment by GrowtopiaNoobs** [comment]
Closing this as it got enough time to get attention.
