### ISSUE TITLE
How to get lasted items.dat (in cache folder only 322kb)

### ISSUE THREAD

**Issue by InjectionZ** [GrowtopiaNoobs/GrowtopiaServer#1209]
title

**Comment by herothedev** [comment]
[items.zip](https://github.com/GrowtopiaNoobs/GrowtopiaServer/files/4271567/items.zip)
heres the latest

**Comment by InjectionZ** [comment]
That is lasted? I was logon to real server and i check my cache. The items.dat size is 322-323kb

**Comment by raiterjaki** [comment]
😳 Now you can't decode/encode items.dat with old stuff.

**Comment by DEERUX** [comment]
The new items.dat is compressed with zlib in order to consume less bandwidth, and they know custom items are being made so they might wanted to avoid this, the new encryption method or key of the name encryption/decrypti n might have been changed, we are investigating this...
Incase theres a new method, it will not be revealed this time, at least I would like to keep it private.
