### ISSUE TITLE
[BUG] Growtopia V3.021 Crashing When Connecting To Private Server

### ISSUE THREAD

**Issue by TimeTopia** [GrowtopiaNoobs/GrowtopiaServer#1212]
Its crashing since the items.dat 300kb, i think its the new items.dat reason...

**Comment by JadlionHD** [comment]
#1211 lol

**Comment by TimeTopia** [comment]
well, we need this fix since its important and it effects all gt players that plays private servers
cuz it effects all of the servers unless they know how to fix this issue

**Comment by DrOreo002** [comment]
I don't think my method will fix ur issue because gt clients now uncompress the items.dat before reading, so sending the already uncompressed one will crash the client. So you do need to send  the compressed items.dat, your crash prolly because invalid packet is being sent because well items.dat is now compressed, you have to run a proxy to take a look at the new way of how gt server send the items.dat

**Comment by FortniteSyr** [comment]
yow timetopia i want ur help pls pls pls come discord
\/////////////////////
 FortniteSyr#0164
////////////////////////
