### ISSUE TITLE
CODE Icon 

### ISSUE THREAD

**Issue by SurekingIGTPS** [GrowtopiaNoobs/GrowtopiaServer#287]
Please who have code icon ubisoft or rtsoft for my gazette 
@SecretHax @OverallGod @ericsnth @GrowtopiaNoobs @NotDark @iRestartz @willi123yao

**Comment by OverallGod** [comment]
Please don't @ me. What do you mean by Code icon

**Comment by Felixcesar15** [comment]
C'mon you should find item id by yourself,we are not mass codefeeders

**Comment by QKVLR** [comment]
Look to coredata and packet list

**Comment by ardakurucim** [comment]
.../rtsoft_logo.rttex maybe

**Comment by FuzionVapes** [comment]
He doesnt know anything lol

**Comment by DrOreo002** [comment]
Can someone ban this guy?

**Comment by jagerrood** [comment]
Seriously, can someone ban this guy?

**Comment by playingo** [comment]
actually tbh a ban is not needed its just some harmless indo who is too lazy or has not enough education 2 do stuff himself, i would actually even appreciate it if he would just ask for the function to do that instead of the whole code, but nope hes one of the too lazy ppl just like 70-75% of the rest.
anyways, didn't wanna offend anyone, just pointed out.

**Comment by QKVLR** [comment]
Realy ban him. 
He spamming issuse.

**Comment by flossboss** [comment]
@QKVLR can we ban u? That kid asking for help if you're not going to help just ignore it smh

**Comment by GrowtopiaNoobs** [comment]
@ardakurucim gave answer to this. If it is not answer you are looking for, then look into CoreData.txt
