### ISSUE TITLE
asd

### ISSUE THREAD

**Issue by ritzysw** [GrowtopiaNoobs/GrowtopiaServer#30]
ah

**Comment by ritzysw** [comment]
some kids are going absolute madness cuz they dc every 1 min so 5 mins still wont work

**Comment by FocusedSG** [comment]
then change the interval to 1 minute?

**Comment by ritzysw** [comment]
now imagine like 20k people being saved every min? that will take like 30 secs atleast to save it so people would just think server went down

**Comment by FocusedSG** [comment]
is it possible to enable real-time saving?

**Comment by ritzysw** [comment]
i tried to make players save every block break but that also makes server lag

**Comment by GrowtopiaNoobs** [comment]
> but when players get unexpectedly disconnected from the server it doesn't count as ENET_EVENT_TYPE_DISCONNECT
I think that it should count. Can you show any case when this happens? We can talk more on discord.

**Comment by ritzysw** [comment]
my old discord got banned, I added you on new one but you weren't online for like 4 days(at least I haven't seen you) so I decided to post here

**Comment by GrowtopiaNoobs** [comment]
So your new discord is now Ritzy#5198?

**Comment by ritzysw** [comment]
yes

**Comment by playingo** [comment]
@ritzysw for levels and only stuff that is being worked by hard work (unlike clothes i hope you get what i mean), you could do an ifstream in ENET_EVENT_TYPE_RECEIVE.
i would only edit the values of levels and gems + use ifstream NOT ofstream (if you use ofstream you are fucked up even if you include the other values because i assume ifstream uses a thread (correct me if i am wrong) to save stuff independently from the server (server doesnt get affected))
and yes, this is actually good real-time saving
