### ISSUE TITLE
Hello guys!

### ISSUE THREAD

**Issue by xDemirHD** [GrowtopiaNoobs/GrowtopiaServer#360]
Hi guys!
I am new in these things. Can someone teach me how to use C++ and ENet together? I am not begging. I like to learn new things. 
For example;
/find [ How to make a menu and add items to the list ]
How to carry out an action like /wban [arg] bans the [arg] ?
I am trying to learn how to make new things.
I am not begging, just teach me the basics.

**Comment by Mempler** [comment]
Hey! it's good that you've asked that, sadly this repository is for Experts in C++ only! we're willing to help with some issues but we're not willing to give anyone some sort of code. but since you're new, i would recommend you to read into some books, watch some Youtube Tutorials etc. Sadly, this is an issue that does NOT belong to this repository since it is NOT a bug report or anything like that!
