### ISSUE TITLE
Rewrite

### ISSUE THREAD

**Issue by ghost** [GrowtopiaNoobs/GrowtopiaServer#52]
Is it possible to rewrite the code of the server? I'm planning to rewrite it in nodejs so i can use many types of databases. Thanks for reply

**Comment by DrOreo002** [comment]
Well we cannot remake it without knowing how it works. You literally got the same question as me

**Comment by willi123yao** [comment]
Well as far as I know, the client and server of Growtopia is coded in C/C++, and the networking library of it is called ENet (basically a network library is something that uses game information  such as text to world info to convert into raw packets that can be sent to others). 

Apparently ENet is made in C/C++ and no one has ported this library over to other languages as far as I know. So far only wrappers for ENet exists but they mostly are very old (the newest ENet wrapper for nodeJS was made 3-4 years ago and never updated since) or lack functionality required.

It would be rather hard to rewrite ENet without decent knowledge of C/C++ as well as the language that it is being rewritten to. The only way I can think of to use other languages such as Java or NodeJS for now would be putting together a hybrid of both languages, meaning that some parts of the code would be in NodeJS/Java while some others would be in C/C++.

**Comment by DrOreo002** [comment]
agree, using other modules prob a good way to solve this problem. But i don't know what librsry is good for this

**Comment by PixelTheGreat** [comment]
Cause i'm really excited to recode this whole thing into NodeJS

**Comment by PixelTheGreat** [comment]
If we use socket.io, we would have to recode the Growtopia Client itself right?

**Comment by OpenSourceWho** [comment]
I'm pretty sure you have to edit the growtopia client to make it work with socket.io.

**Comment by PixelTheGreat** [comment]
Yeah, it's written in C++ right?

**Comment by OpenSourceWho** [comment]
It is written in C & C++ i think.

**Comment by OpenSourceWho** [comment]
Get visual studio, start debugging it and try to find how it takes requests.

**Comment by PixelTheGreat** [comment]
the .exe itself?

**Comment by OpenSourceWho** [comment]
Yeah you can debug exe's in visual studio.

**Comment by PixelTheGreat** [comment]
Wait, so if we do found out how it takes requests, we have to make our own .exe?

**Comment by OpenSourceWho** [comment]
No just find out how it takes requests mostly by debugging then start rewriting the protocol in NodeJS.

**Comment by PixelTheGreat** [comment]
ahh okay, no need to recode the Growtopia .exe?

**Comment by OpenSourceWho** [comment]
Yeah no need to rewrite it.

**Comment by willi123yao** [comment]
I don't think there is a way to use any other library than ENet due to the fact that the Growtopia client is also using the ENet library, like which @OpenSourceWho has mentioned, you would need to rewrite the entire client as well to make it able to use any other libraries, which is equivalent to creating another Growtopia game in a complete different programming language.

I am still looking into trying to do it the hybrid way, by using native modules for nodeJS (https://nodejs.org/api/addons.html) but still would pretty much require rewriting the source code to make it usable with NodeJS (the main program is roughly 3000+ lines, you can estimate the amount of work needed), as well as doing type conversion since some of the variable types used do not have a NodeJS equivalent.

**Comment by willi123yao** [comment]
I have done that, but you can try implementing the growtopia server (all the enet initialization stuff are in the _tmain function of the source code (enet server test.cpp), and I don't think it has functionality or support for packet/payload checksum, which is needed for the server.

**Comment by GrowtopiaNoobs** [comment]
I looked at this library https://github.com/mnaamani/enet-npm and it looks fine. It is probs easiest to cheat up a bit and edit jsapi.c jsapi_enet_host_create_server and there setup range compress and crc. I think that it might be kinda cool to make all this run under browser, but there would be need to rewrite enet to javascript, cuz I just found that stuff like this https://developer.chrome.com/apps/sockets_udp exists, even if it is supported only for browsers extensions. And there shouldn't be problems with datatypes, but with low level operations because you need byte arrays where you memcpy all numbers, strings, etc.

**Comment by PixelTheGreat** [comment]
NodeJS is not for browser though, but it might work

**Comment by PixelTheGreat** [comment]
@GrowtopiaNoobs Can you  like make a flowchart on how the server works?

**Comment by willi123yao** [comment]
Yeah, it is possible to make some changes to the library so that it works on NodeJS, however Emscripten compiles it to Javascript which might affect performance, also mostly worried about Javascript Numbers, which only have precision up to 2^53, and therefore long int variables might be affected as they go up to 2^64.

**Comment by PixelTheGreat** [comment]
i think it's possible to edit the long int variables, but editing the lib? enet? i don't do cpp

**Comment by PixelTheGreat** [comment]
i need a flowchart on how it works :sob:

**Comment by willi123yao** [comment]
There is an ENet module (nodeJS module) for NodeJS, but however like GrowtopiaNoobs has mentioned, it is lacking the checksum feature and the range compressor which can be included by editing the library(module) and then recompiling the module so that it has the features needed to make a Growtopia Server.

As for the flowchart, there isn't really a flowchart that exists and most of it is inside the server code, and it would be really good to familiarise yourself with the source code that GrowtopiaNoobs has made and by looking through that and trying to figure out the general process(or flow) of the server.

**Comment by OpenSourceWho** [comment]
^

**Comment by DrOreo002** [comment]
Hmmm, nice point. Seems like we have to do some research by our own here, alright. Will do it, thanks

**Comment by GrowtopiaNoobs** [comment]
Long integers are not problems, because it is used in my code to handle time, so you can use Date in javascript instead. And I can't really make any easy flow chart as there is alot of stuff to explain. But mostly it is just infinite loop which handle packets and peers connection and disconnections, then it decodes packet. Based on first 4 bytes it select type of decoding. There are some empty packets, then packets which contains plain text. Most important there are packets which contains player data struct (56 bytes) and they have its own types. Based on that second type you choose if it is punch, move, item drop or anything. Server then responds with packets which looks mostly same, but some of them contains variant list (I call it in source GamePacket). Which is used for most of actions instead of plain text. And it is all just about recieving and sending right packets to right peers.

**Comment by PixelTheGreat** [comment]
@GrowtopiaNoobs will this work?
https://github.com/zpl-c/enet

for enet on nodejs

**Comment by DrOreo002** [comment]
You can use swig instead to compile it, I'm currently reworking the server to work with java

You can take a look at their website

**Comment by PixelTheGreat** [comment]
I mean i just found it online. Its made for nodejs. I was asking if it's better than enet-npm? This one is made in C tho for nodejs

**Comment by willi123yao** [comment]
@PixelTheGreat Not to let you down or anything, but as far as I can see and tell, that library so far has no interfaces provided in nodejs and is purely in C/C++, even in the documentation you can see that there is zero javascript related code at all (maybe its just that it hasn't been developed, no one knows and it is impossible to use it in this state). Just by looking at the intro and filetype breakdown of that repo really makes me doubt if it is even going to be a nodejs library:

![en43d](https://user-images.githubusercontent.com/26355099/48843458-15d51000-edd2-11e8-8a01-fc72b40c98f6.png)

**Comment by PixelTheGreat** [comment]
yeah they told me it was for C :sob:

**Comment by GrowtopiaNoobs** [comment]
This wan't active for long time and some of us joined to developers group, so I think this can be closed

**Comment by damianmcclure** [comment]
I'd like to reopen this. I'm attempting to do this in NodeJS as well because it would be way simpler for me to add features in a language I can understand. The only problem is it seems like that enet-npm module either doesn't work or is just not made for this type of use. I can't seem to receive packets in any way using that module. I'd need more help to do something like this because I cannot do it by myself.

**Comment by coldchip** [comment]
@damianmcclure Last year, I had tried it but to no avail, even gone as far to compile the ENet C code into JavaScript ASM, nah no luck because of how NodeJS Raw Sockets works. It don't support CRC32 checksum on raw UDP packets. I also don't recommend using JavaScript because how Threads work on this language.

**Comment by kuteshiki** [comment]
Hello, I've never liked c++
but I really wanted to make a growtopia server so I tried many times to learn this language but it's too messy for me and this project too.
So now, I wanted to rewrite this in node.

After snooping around a bit: I found
https://www.npmjs.com/package/node-growtopia
https://www.npmjs.com/package/raw-socket
https://expressjs.com/
I myself use express a lot so I think this could work.

**Comment by OverallGod** [comment]
Did you even read what they said

**Comment by damianmcclure** [comment]
@coldchip yeah but then whats the point. To my knowledge none of the NodeJS libraries support the encoding needed to talk with Growtopia. NodeJS is so stupid for something like this anyway, theres too much overhead and its no where near as efficient as c++ would be.
