### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ZentaiZber** [GrowtopiaNoobs/GrowtopiaServer#666]
How to fix dice block is always show number 1 wtf?

**Comment by playingo** [comment]
i dont think anyone found out a "fix" for that because simply almost no one knows how to communicate more specifically with tiles except @noob (ilyn in this github) and maybe 1 other person.
its basically like the wl has a green lock (visually) on it but its not a different item id.
the one who would know how to communicate more specifically with tiles though can also make proper signs.

**Comment by playingo** [comment]
p.s dont dm @noob or so im pretty sure he will never give it to you or say any stuff except you have some money/dls in your pocket

**Comment by willi123yao** [comment]
Closing this issue as it seems inactive/resolved.
