### ISSUE TITLE
Growtopia Is Closing When Trying To Enter World

### ISSUE THREAD

**Issue by iNPGT** [GrowtopiaNoobs/GrowtopiaServer#678]
Gt is closing after entering world
![image](https://user-images.githubusercontent.com/44301044/60705737-8c152580-9f10-11e9-91f4-ad1dd1515ba2.png)

**Comment by noobesgt** [comment]
Try to delete the worle or this may be caused from entering lag. This happends to me too. Re-open gt and try again

**Comment by iNPGT** [comment]
I have tried everything, just crashing...

**Comment by ardakurucim** [comment]
@iNPGT I think you are using old cpp am i right? because program couted Entering some world... Try to enter worlds like TEST

**Comment by willi123yao** [comment]
If possible, please do compile and run your code in debug mode and provide the stacktrace of your program after it crashed so that we can look into the problem and provide you help on the matter.

Also, be sure to use the latest update from this repository and do be reminded that any unofficial/modified code that you obtained from elsewhere (someone else or some other place) that is not from this repo is not supported by us.

Closing this also since it seems to be inactive/resolved.
