### ISSUE TITLE
Is there really a way to fix Record growtopia1.com to localhost already found?

### ISSUE THREAD

**Issue by HelpmeHelpyous** [GrowtopiaNoobs/GrowtopiaServer#77]
When I placed 127.0.0.1, then it said:
Record growtopia1.com to localhost already found!
When I removed it, there is the wine stuff idk

When there was record growtopia1.com to localhost already found,
I would be stuck in the log in screen.
I've updated my growtopia to the latest version, updated cpp into the latest version and prepared every single file needed. (I've followed the wiki, it's still not working!)

Can anyone please help me? If not then i quit

**Comment by DrOreo002** [comment]
Do you still need help?.

If you still need help can you please answer this question?

What OS that ur running on? (Windows, Linux, etc)
Are you using the python start program to start the server?

Also you don't really need to update cpp since the server startup is handled on the python program. Also you could try IDA Pro and find the address for growtopia1 and change it to localhost (127.0.0.1) I'm not going to give full in depth tutorial because its kinda complicated to do

**Comment by Dunzap** [comment]
> Do you still need help?.
> 
> If you still need help can you please answer this question?
> 
> What OS that ur running on? (Windows, Linux, etc)
> Are you using the python start program to start the server?
> 
> Also you don't really need to update cpp since the server startup is handled on the python program. Also you could try IDA Pro and find the address for growtopia1 and change it to localhost (127.0.0.1) I'm not going to give full in depth tutorial because its kinda complicated to do

I'm running Windows 10.
Im using Python IDLE to run http server.

**Comment by DrOreo002** [comment]
@Dunzap Hmmm, try to use python 3.0 maybe?. Also check if the port for the gt server is actually availabe or online

**Comment by Mempler** [comment]
Duplicate to #71
