### ISSUE TITLE
[VPS HELP] I got a vps (xampp is setuped)

### ISSUE THREAD

**Issue by coldtopia** [GrowtopiaNoobs/GrowtopiaServer#783]
I got a vps,and xampp is setuped like add growtopia folder and serverdata.php in it, and change port 80 to 8080 but still error connecting.Im new here XD

**Comment by moanhawks** [comment]
You cannot change 80 to 8080 bcz HTTPrequest is using 80 port

**Comment by Deveytv** [comment]
Hm :ok:

**Comment by coldtopia** [comment]
> You cannot change 80 to 8080 bcz HTTPrequest is using 80 port

oh ok

**Comment by herothedev** [comment]
CDNContent or server_data.php setupped wrongly.

**Comment by Eleven-Dev** [comment]
Thanks for sharing, simply add 80 and 17091 in google cloud and simply link it to vps with a Tag and then go to vps and make a firewall rule called "433" inbound then setting up xampp if thats your issue is simply downlaod xampp and open it as admin and start the 2nd one and them go to config and chamge 80 to 8080 because 80 is already in use if your running server.exe (btw open config on the 1st one also start it so clearly 1-2 is started) now open xampp path in file Explorer and find docs in xampp main folder and open it and but server.php in it (with growtopia folder with)

**Comment by Eleven-Dev** [comment]
Btw hi coldtopia!

**Comment by coldtopia** [comment]
okay
