### ISSUE TITLE
Save dropped item's

### ISSUE THREAD

**Issue by OverallGod** [GrowtopiaNoobs/GrowtopiaServer#797]
I could just save the x and y every time an item is dropped then send the drop code when they enter and when they take it delete the x and y but that's not very efficient.
 Any idea's on how to efficiency save and efficiency send items?

**Comment by playingo** [comment]
i would use memory for dropped items and when closing server it saves. use array probably... idk if its true but there was a way to memcpy full dropped items in world with loop (havent tried it out + idk how to specifically do that i dont even know offsets for the dropping when entering) but that should do it according to what ive heard from others.

the point is: i would suggest you to do more investigation on the real gt servers (cuz that probably was the golden way to get stuff like block visuals aka signs and etc) and probably also might be a way when doing something like this.
use gtbot + log stuff to file to investigate...
but tbh, im doing the "inefficient" way that you mentioned and it works pretty much ok if u use memory and not read from a file or something...

**Comment by playingo** [comment]
but tbh esto / mar4ello was the 1 who made signs working as it used to be complex for me too but eventually, esto / mar4ello gave it exclusively to me for alot of crash fixes and others... 
but since we are talking about gems, the inefficient way should do it for now and if you really need a more efficient way, look at how gt server does it with bot and stuff... (there is a slight little chance that they also do it in the way you mentioned but i dont really think so, although theres a slight chance)...

**Comment by OverallGod** [comment]
Alright
thanks
