### ISSUE TITLE
Who Can give CoreData 😁❤

### ISSUE THREAD

**Issue by kingawesomed2** [GrowtopiaNoobs/GrowtopiaServer#825]
Hello, Can Anyone Give Coredata Or Say How to Get New Coredata?❤😁

**Comment by Lapada** [comment]
no ❤😁

**Comment by kingawesomed2** [comment]
:(

**Comment by Tumppi05098** [comment]
U can build it with ur self.

**Comment by Tumppi05098** [comment]
But if u want i can give my coredata if u tell me ur discord name

**Comment by kingawesomed2** [comment]
@Tumppi05098 bex#4685

**Comment by Secret-8179** [comment]
Hello Everyone This Is GTIO FULLY FOLDER! If You Want to know what the Password of the Exe Dm Me! Discord name: Secret#8179 And Don't hate me Because There are Someone Of gays Send to me Link 5 Seconds I was lucky Copying the link faster! His Name Valkrie! XD Have Good Time! https://github.com/Secret-8179/GTIOFOLDER

**Comment by Deveytv** [comment]
> Hello, Can Anyone Give Coredata Or Say How to Get New Coredata?❤

Close this issue.

**Comment by GrowtopiaNoobs** [comment]
Closing this, because it is too old.
