### ISSUE TITLE
NEED HELP! How i can add roles break bedrock?

### ISSUE THREAD

**Issue by Tumppi05098** [GrowtopiaNoobs/GrowtopiaServer#828]
I mean how i can make admins and above roles acces to break bedrock?
(No hate or trolling plis)

**Comment by OverallGod** [comment]
Do you even know anything about c++

**Comment by kingawesomed2** [comment]
@overallgod yeah how do i when search bedrock enetcpp nothing found

**Comment by OverallGod** [comment]
I think the ID for bedrock is 8

**Comment by kingawesomed2** [comment]
@overallgod How Give access too Mod For Break bedrock

**Comment by Tumppi05098** [comment]
ye that i mean

**Comment by kingawesomed2** [comment]
@tumppi05098 my discors bex#4685 can give coredata

**Comment by VyteGTPS** [comment]
#trash

**Comment by Secret-8179** [comment]
Hello Everyone This Is GTIO FULLY FOLDER! If You Want to know what the Password of the Exe Dm Me! Discord name: Secret#8179 And Don't hate me Because There are Someone Of gays Send to me Link 5 Seconds I was lucky Copying the link faster! His Name Valkrie! XD Have Good Time! github.com/Secret-8179/GTIOFOLDER

**Comment by playingo** [comment]
TUMPPI UR ASKING WAY TOO MUCH TRY TO FIND A WAY YOURSELF FIRST OR GOOGLE ABOUT SOME STUFF BEFORE ASKING IN HERE. THIS IS A PRIVATE SERVER GITHUB NOT A GITHUB FOR C++ BASICS!!!

**Comment by Tumppi05098** [comment]
Okay @playingo
