### ISSUE TITLE
Does anyone know cant long punch with punch effect?

### ISSUE THREAD

**Issue by ardakurucim** [GrowtopiaNoobs/GrowtopiaServer#849]
Example : when i type /p 10 only space can punch but when i type /p -502 There is long punch how to fix it?

**Comment by ardakurucim** [comment]
Or when i change onspawn smstate to 1 it works but with longest punch

**Comment by playingo** [comment]
yes its different ids its like very long positive ids and not minus ids if u want to find them out reverse gt otherwise u cant.
also mstate = *mod*state (long zoom and unlimited jump but no unl punch/place)
smstate = supermod state basically reg4shis or dev power its what ive mentioned in mstate except it got long punch/place too

**Comment by ardakurucim** [comment]
@playingo wdym with reverse gt?

**Comment by ardakurucim** [comment]
@playingo also ik positive long ids works but gtsg has it

**Comment by ardakurucim** [comment]
without positive long ids

**Comment by herothedev** [comment]
@ardakurucim if u dont want to use negatives just make that minium number is 0.

**Comment by ardakurucim** [comment]
@herothedev i already blocked it i mean /p 10 only can punch with space not mouse.

**Comment by ardakurucim** [comment]
nevermind found it used this = 
((PlayerInfo*)(peer->data))->effect = 8421376 + stoi(str.substr(3, cch.length() - 3 - 1));
