### ISSUE TITLE
[BUG] enet server test.exe crashing

### ISSUE THREAD

**Issue by Avier1** [GrowtopiaNoobs/GrowtopiaServer#879]
[](https://gyazo.com/322612b0780febefb07eae26f9f09d5f
)

It's just crashing, run.py is working fine.

Also, there are no worlds or players so deleting any wouldn't fix it.

**Comment by Zlarex** [comment]
is there any worlds and players folder? and can you describe why that happened?

**Comment by herothedev** [comment]
(if you are using your exe on public use): 
You need to figure out crash bugs, because some guys uses them to get servers down.

(if you are running it locally and not crashing it urself):
Delete all worlds and players what are 0kb, if you added any unmerged pull req, make sure you have all required folders and there isnt errors.

**Comment by Avier1** [comment]
I found out the problem, thanks.

I didn't have CoreData.txt

**Comment by VyteGTPS** [comment]
retard
